baseURL = 'https://jk123jkl.github.io/'
languageCode = 'en-us'
title = '123jk Site'
theme = 'hello-friend-ng'
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "woo yeah"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu =false 

  # Metadata mostly used in document's head
  description = "Test"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "123jk's site"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  [languages.en.params]
    subtitle  = "yes"

    [languages.en.params.logo]
      logoText = "123jk"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"

  [[menu.main]]
    identifier = "blogs"
    name       = "Blog"
    url        = "/posts"

  [[menu.main]]
    identifier = "cubes"
    name       = "Cube"
    url        = "/cubes"

  [[menu.footer]]
    identifier = "rats"
    name       = "Rats"
    url        = "/rats"
